### What is tensor?
I mathematics, a tensor is an algebric object that describe a multilinear relationship between sets of algebraic objects related to a vector spasce. Objects that tensors may map between include vectos and scalars, and even other tensors.

In pytoch 

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters. Tensors are similar to NumPy's ndarrays, except that tensors can run on GPUs or other hardware accelerators.

### What is PyTorch?

PyTorch is Machine Learning and Deep Learning Library

### PyTorch WorkFlow

In [7]:
%%html
<img src="pytorch_workflow.png" style="height:300px">

In [8]:
import torch
print(torch.__version__)

2.10.0


#### Introduction to tensors

In [9]:
import torch 
# scalar 
scalar = torch.tensor(7)
scalar 

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
scalar.item() # tensor back as int DataType

7

In [12]:
# Vector 
vector=torch.tensor([7,7])

In [13]:
vector 

tensor([7, 7])

In [15]:
%%html
<img src="scalar_vector_matrix_tensor.png" style="height:250px">

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
# MATRIX
matrix = torch.tensor([[10,2],[12,3]])
matrix
matrix.ndim
matrix.shape

torch.Size([2, 2])

In [19]:
matrix

tensor([[10,  2],
        [12,  3]])

In [20]:
matrix.ndim

2

In [21]:
matrix[0]

tensor([10,  2])

In [22]:
matrix[1]

tensor([12,  3])

In [23]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
%%html
<img src="tensor-dimensions.png" style="height:300px">


##### Tensor - an n-dimensional array of numbers 
The dimensions go outer to inner.

That means there's 1 dimension of 3 by 3.


#### Random TENSORS

Random TENSORS are important that the way the many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represnet the data.

`Start with random numbers --> Look at data --> update random numbers --> look at data --> update random numbers`

In [28]:
 # Create a random tensors of size or shapr (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8141, 0.7255, 0.1665, 0.8349],
        [0.3234, 0.0048, 0.0909, 0.5462],
        [0.7634, 0.8916, 0.0311, 0.7771]])

In [29]:
random_tensor.shape

torch.Size([3, 4])

In [30]:
random_tensor.ndim

2

In [31]:
# Create a random tensor with similar shape to an image tensor 

random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width, colour channels (R,G,B)
random_image_size_tensor.shape ,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [33]:
### tensors with zeros and One's
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# with size parameter 
torch.rand(size=(10,10))

tensor([[0.4785, 0.1542, 0.3680, 0.1885, 0.7385, 0.8699, 0.2266, 0.6009, 0.5831,
         0.6460],
        [0.9167, 0.7760, 0.5879, 0.4752, 0.4933, 0.9566, 0.5205, 0.0036, 0.7663,
         0.0655],
        [0.6704, 0.4318, 0.5207, 0.2822, 0.7222, 0.4749, 0.1228, 0.0380, 0.9448,
         0.7136],
        [0.9189, 0.7217, 0.6487, 0.4074, 0.3917, 0.3258, 0.4893, 0.3746, 0.1708,
         0.9799],
        [0.8391, 0.5424, 0.0746, 0.0247, 0.1588, 0.3885, 0.4878, 0.9111, 0.4335,
         0.0782],
        [0.6262, 0.0903, 0.2852, 0.1364, 0.3584, 0.2297, 0.9986, 0.6083, 0.5172,
         0.2803],
        [0.5022, 0.3325, 0.9849, 0.5818, 0.8239, 0.7520, 0.7344, 0.3094, 0.1444,
         0.0435],
        [0.2696, 0.4598, 0.9639, 0.9828, 0.6379, 0.1370, 0.1092, 0.8530, 0.4435,
         0.1024],
        [0.8885, 0.8839, 0.4712, 0.9244, 0.9071, 0.5259, 0.0102, 0.9826, 0.4889,
         0.1197],
        [0.0222, 0.8036, 0.6244, 0.1052, 0.5462, 0.9460, 0.1022, 0.1626, 0.9050,
         0.3294]])

In [35]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# Create One's
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype

torch.float32

In [41]:
random_tensor.dtype

torch.float32

##### Random zeros ---> This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

### Cerate tensors of rangs and tensor-like

In [42]:
torch.range(0,10)

/var/folders/qw/1yjf9b510s9313l0fhws6lrw0000gn/T/ipykernel_1381/497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
one_to_zero = torch.arange(0,10)
one_to_zero

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
torch.arange(start=0,step=10,end=100)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
one_to_zero.shape

torch.Size([10])

In [47]:
# tensor-like
ten_zeros = torch.zeros_like(one_to_zero)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor DataTypes

In [52]:
# Float32 --> A number that contains 32 bit in computer Memory
# Precision of a numerical quantitity is a measure of the detail in which the Quantity is expressed
float_32_tensor = torch.tensor([3.0,6.0,10.0],dtype=None) # Even dtype is None it will shows float
float_32_tensor

tensor([ 3.,  6., 10.])

In [53]:
float_32_tensor.dtype

torch.float32

In [55]:
# datatype = datatype is tensor , This is the first thing that when we create tensor
# required_grad = Whether or not to track gradients
float_32_tensor = torch.tensor([3.0,6.0,10.0],dtype=None,device="cpu",requires_grad=False)
float_32_tensor

tensor([ 3.,  6., 10.])

In [56]:
# float16 Tensor
float_16_tensor = float_32_tensor.type(torch.float16)

In [57]:
float_16_tensor


tensor([ 3.,  6., 10.], dtype=torch.float16)

In [59]:
# int32 tensor * float 32 tensor
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [60]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 90.])

In [61]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 90.], dtype=torch.float16)

#### Getting Information from Tensors

1. Tensors not right datatype -> to do get datatype from a tensor , can use `tensor.dtype`
2. Tensors not right shape -> to get shape from a tensor, can use `tensor.shape`
3. Tensor not on right device -> to get device from a tensosr use `tensor.device`

In [62]:
# Create a tensor 
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4931, 0.4069, 0.5441, 0.4603],
        [0.2681, 0.0936, 0.0160, 0.6654],
        [0.9502, 0.7680, 0.2044, 0.7084]])

In [63]:
# Find the details of the some_tensor
print(some_tensor)
print(f"Datatype of some_tensor : {some_tensor.dtype}")
print(f"Size of the some_tensor: {some_tensor.size()}")
print(f"Shape of the some_tensor: {some_tensor.shape}")
print(f"Tensor Device on : {some_tensor.device}")

tensor([[0.4931, 0.4069, 0.5441, 0.4603],
        [0.2681, 0.0936, 0.0160, 0.6654],
        [0.9502, 0.7680, 0.2044, 0.7084]])
Datatype of some_tensor : torch.float32
Size of the some_tensor: torch.Size([3, 4])
Shape of the some_tensor: torch.Size([3, 4])
Tensor Device on : cpu


#### Manipulating Tensors (Tensor Operations)

Tensor operations include 
 - Addition
 - Subtraction
 - Multiplication (element-wise)
 - Division
 - Matrix multiplication

In [64]:
# Create a Tensor 
tensor = torch.tensor([1,2,3])

tensor+10 # Addition 

tensor([11, 12, 13])

In [65]:
# Multiply tensor by 10 
tensor*10

tensor([10, 20, 30])

In [66]:
# subtraction 
tensor - 10

tensor([-9, -8, -7])

In [67]:
# Division 
tensor//10

tensor([0, 0, 0])

In [68]:
# Torch in-built function 
torch.mul(tensor,10)

tensor([10, 20, 30])

In [69]:
torch.add(tensor,10)
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [70]:
torch.sub(tensor,1)

tensor([0, 1, 2])

In [71]:
%%html
<img src="matrix-multiplication.png" style="height:300px">

#### Matrix multiplication 
Two main ways of performing multiplication in neural network and deep learning 

- Element Wise multiplication
- Matrix multiplication

In [72]:
%%html
<img src="matrix-multiply-dot.svg" style="height:300px">

#### The dot product is where we multiply matching members, then sum up:

(1, 2, 3) • (7, 9, 11)= 1×7 + 2×9 + 3×11
= 58
We match the 1st members (1 and 7), multiply them, likewise for the 2nd members (2 and 9) and the 3rd members (3 and 11), and finally sum them up.

In [73]:
# Element wise multiplication 
tensor

tensor([1, 2, 3])

In [74]:
tensor*tensor

tensor([1, 4, 9])

In [76]:
# Matrix Multiplication 
torch.matmul(tensor,tensor) # 1*1 + 2*2 + 3*3 = 14

tensor(14)

In [77]:
%%time
value = 0 
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.86 ms, sys: 1.87 ms, total: 3.73 ms
Wall time: 2.08 ms


In [78]:
%%time 
torch.matmul(tensor,tensor)

CPU times: user 267 μs, sys: 68 μs, total: 335 μs
Wall time: 310 μs


tensor(14)

### There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimension** must match:
   * `(3,2) @ (3,2)` This won't work
   * `(2,3) @ (3,2)` This will work
   * `(3,2) @ (2,3)` This will work
2. The resulting matrix has the shape of the **outer dimensions**:
   * `(2,3) @ (3,2) -> (2,2)`
   * `(3,2) @ (2,3) -> (3,3)`

In [79]:
torch.matmul(torch.rand(3,2),torch.rand(3,2)) # This will throws an error (Most Common Error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [82]:
torch.matmul(torch.rand(2,3),torch.rand(3,2)) # This will  work

tensor([[1.0611, 0.6705],
        [0.6515, 0.9586]])

In [83]:
torch.matmul(torch.rand(3,2),torch.rand(2,3)) # This will work

tensor([[0.1865, 0.9170, 0.7218],
        [0.3737, 1.3764, 0.9526],
        [0.2432, 0.5651, 0.2658]])

#### One of the most common errors in the deep learning: Shape Errors



In [84]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_A.shape

torch.Size([3, 2])

In [85]:
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_B.shape

torch.Size([3, 2])

In [86]:
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

#### Transpose --> we can manipulate the tensor shape issue 
A **transpose** switches the axes or dimensions of a given tensor.

In [87]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [88]:
tensor_B


tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [91]:
torch.matmul(tensor_A,tensor_B.T) # Transpose matches the inner dimension and this will not complain about the shape

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [92]:
%%html
<img src="transpose.jpeg" style="height:300px">

#### Finding the min,max, mean , sum etc (tensor aggregation)

In [2]:
import torch 
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
# Find the mean
torch.min(x), x.min()

(tensor(0), tensor(0))

In [5]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [6]:
# tensor x datatype
x.dtype

torch.int64

In [7]:
# Find the mean
torch.mean(x.type(torch.float32)) # need to convert to float before getting the mean

tensor(45.)

###### torch.mean() function requires a tensor of float32 datatype to work

In [8]:
# Find sum
torch.sum(x)

tensor(450)

#### Find the positional min and max

In [9]:
x 

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
# Find the position in tensor that has the minimum value with argmin() -> returns index 
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [11]:
torch.argmin(x)

tensor(0)

In [12]:
# Find the position in the tensor which has the maximum value
torch.argmax(x)

tensor(9)

In [13]:
x[9]

tensor(91)

##### reshape , stacking, squeezing and unsqueezing tensors

In [14]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

##### Reshape 
 - reshapes an input tensor to a defined shape
 -  view - Return a view of an input tensor of certain shape but keep the sampe memory
##### stacking
 - stacking multiplitple tensor , (contactinate tensors)
##### squeeze
 - remove all `1` dimensions from a tensor
##### unsqueeze
 - add a `1` dimension to a target tensor

##### permute 
 - Return a view of the input with dimensions permuted(swapped) in a certain way

In [15]:
import torch
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [18]:
# Reshape 
x_reshaped = x.reshape(1,9) # Add one dimension
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [23]:
x_reshaped = x_reshaped.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [25]:
x_reshape = x.reshape(3,3)
x_reshape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [26]:
x_reshape.shape

torch.Size([3, 3])

In [29]:
#change the view , view share the same memory as the original input
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [31]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [32]:
# stack tensors on top of each other 
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [33]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [34]:
%%html
<img src="squeeze.png" style="height:300px">

#### Squeeze and Unsqueeze notes
unsqueeze() "adds" a superficial 1 dimension to tensor (at the specified dimension), while squeeze removes all superficial 1 dimensions from tensor.

A 1 dimension is superficial in the sense that it does not add any more elements to the tensor than would be there without it. Whenever this is true of a tensor dimension, it will always have the size 1 - hence the name "1 dimension".

You should look at tensor's shape attribute to see it easily. In your last case it would be

In [35]:
import torch
tensor = torch.tensor([1,9,0,2,3,4])
tensor.shape,tensor.size

(torch.Size([6]), <function Tensor.size>)

In [36]:
tensor.unsqueeze(dim=0)

tensor([[1, 9, 0, 2, 3, 4]])

In [37]:
tensor.unsqueeze(dim=0).shape

torch.Size([1, 6])

In [38]:
tensor.squeeze()

tensor([1, 9, 0, 2, 3, 4])

In [39]:
tensor.squeeze().shape

torch.Size([6])

In [40]:
# torch.permute - rearranges the dimenssions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height,width,color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # for color channel axis 0->1 1->2 2->0
print(f"previous shape: {x_original.shape}")
print(f"permutead shape: {x_permuted.shape}")


previous shape: torch.Size([224, 224, 3])
permutead shape: torch.Size([3, 224, 224])


#### Indexing (selecting data from tensors)
##### Indexing with PyTorch is similar to indexing with NumPy

In [41]:
# Creating a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [42]:
# Lets index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
# Let's index on the middle braces
x[0][0]

tensor([1, 2, 3])

In [47]:
x[0][1] # index on the 2nd dimension

tensor([4, 5, 6])

In [49]:
x[0][2] 

tensor([7, 8, 9])

In [50]:
x[0][0][0]

tensor(1)

In [51]:
x[0][0][1]

tensor(2)

In [52]:
x[0][1][1]

tensor(5)

In [53]:
x[0][1][0]

tensor(4)

In [54]:
x[0][2][2]

tensor(9)

In [55]:
x[:,0]

tensor([[1, 2, 3]])

In [56]:
# Get the all values of 0th and 1st dimensions but only index of 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [57]:
# get all values of 0th dimension but only the 1 index  value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [58]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

#### PyTorch tensors & NumPy
##### Numpy is a popular scientific Python numerical computing library
##### And because of this , PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarry)`
* PyTorh tensor -> Numpy -> `torch.Tensor.numpy()`

In [60]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [61]:
# numpy default DataType
array.dtype

dtype('float64')

In [64]:
# Default Datatype of torch tensor
# When converting from numpy to torch, pytorch converted to numpy default data type to float64
x = torch.arange(1.0,8.0)
x.dtype

torch.float32

In [65]:
# Change the value of an array , what will this do to tenosr?
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [66]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [67]:
numpy_tensor.dtype

dtype('float32')

In [68]:
# Change the value of tensor, what will do numpy?
tensor = tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#### Reproducability (Trying to take random out of random)
##### In short how a neural network leans
`start with random numbers -> tensor operataions -> update random numbers to try and make them of the data  -> again -> again -> again`

To reduce the randomness in neural networks in PyTorch comes the concept of a **random seed**
Essentially what the random seed does is "flavour" the randomness

In [70]:
torch.rand(3,3)

tensor([[0.4110, 0.1781, 0.8006],
        [0.5249, 0.8589, 0.3816],
        [0.3704, 0.9620, 0.4947]])

In [71]:
import torch
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4685, 0.5055, 0.3716, 0.9114],
        [0.0490, 0.0413, 0.8846, 0.1643],
        [0.7893, 0.6941, 0.7527, 0.7803]])
tensor([[0.3241, 0.5194, 0.5265, 0.2536],
        [0.9378, 0.0135, 0.0600, 0.4171],
        [0.8005, 0.0283, 0.1231, 0.1714]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [73]:
# Let's make some random but reproducable tensors

import torch

# Set the random seed 
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#### RANDOM_SEED
A random seed is an integer used to initialize a deterministic algorithm that generates sequences of numbers which appear random.

a random seed is an initial value used to control all pseudo-random number generators (PRNGs) so that experiments become reproducible.

In [75]:
### Check for isGPU available
import torch
torch.cuda.is_available()

False

In [76]:
# Setup device agnostic Code 
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [77]:
# For Mac Silicon 
import torch
if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

device

device(type='mps')

In [82]:
# To use mps with pytorch

import torch

device = (
    "mps"
    if torch.backends.mps.is_available()
    else
    "cpu"
)
x = torch.randn(10000,10000,device=device)
y = torch.matmul(x,x)
print(device)
print(x)
print(y)

mps
tensor([[ 0.2223, -0.6956,  0.2011,  ..., -0.6336, -2.0623, -1.0794],
        [-0.1960, -0.1903, -0.1493,  ...,  0.0615,  0.0514, -0.5373],
        [-1.9035,  0.5984,  2.3908,  ...,  0.2898, -0.5479,  0.7962],
        ...,
        [ 0.8675,  0.1227,  1.0638,  ..., -0.2004,  1.3137,  0.6197],
        [-0.9886,  0.2902, -0.1318,  ...,  0.1539, -0.1196,  0.0528],
        [-0.3762,  0.4959, -0.7031,  ...,  0.4322, -0.6832, -1.4177]],
       device='mps:0')
tensor([[  58.9093,   23.5172,   47.6043,  ...,   98.8263,    2.7527,
           57.9180],
        [ -41.7132,   29.3501,  104.7650,  ...,  -68.2052,   -7.5641,
           56.7389],
        [  70.7856,   95.8727,   47.0219,  ...,   70.6621,  116.7603,
           -6.9562],
        ...,
        [ 124.4949,  -30.4709,  120.2723,  ...,   -3.0412,   40.6304,
         -103.3198],
        [-105.9627,   23.6583,   60.6321,  ...,  -80.4468,  -19.4627,
         -206.1235],
        [  95.4412, -171.4668,   30.3489,  ...,  -47.7732,  -86.4737,
 

##### # To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()